apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delta-4125gs-pvc5
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 7153Gi
  storageClassName: local-sc
