apiVersion: v1
kind: ConfigMap
metadata:
  name: bertconfig
  namespace: openshift-local-storage
data:
  DGXNGPU: "5"
  BATCHSIZE: "90"
  PACKING_FACTOR: "2"
  GRADIENT_STEPS: "1"
  LR: "0.00064"
  MAX_SAMPLES_TERMINATION: "4500000"
  MAX_STEPS: "3680"
  OPT_LAMB_BETA_1: "0.60466"
  OPT_LAMB_BETA_2: "0.85437"
  START_WARMUP_STEP: "0"
  WARMUP_PROPORTION: "0.0"
  WEIGHT_DECAY_RATE: "0.1"
  INIT_LOSS_SCALE: "1024.0"
  EXTRA_PARAMS: "--dense_seq_output --pad_fmha --fused_bias_fc --fused_bias_mha --fused_dropout_add --fused_gemm_gelu --packed_samples --use_transformer_engine2 --cuda_graph_mode 'segmented' --use_cuda_graph "
  PHASE: "2"
  EVAL_ITER_START_SAMPLES: "150000"
  EVAL_ITER_SAMPLES: "150000"
  DGXNNODES: "1"
  DGXSYSTEM: "DGXH100"
  WALLTIME_MINUTES: "8"
  DGXSOCKETCORES: "64"
  DGXNSOCKET: "2"
  DGXHT: "2"
  WALLTIME: "85"
  SLURM_NTASKS: "5"
